name: GitHub-Profile-3D-Metric

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run
jobs:
  build:
    runs-on: ubuntu-latest
    name: Metrics embed
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@v3.34

      - name: Commit & Push
        run: |
            
